/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as ConsumptionRouteImport } from './routes/consumption'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MeterRouteImport } from './routes/meter'
import { Route as PaymentsRouteImport } from './routes/payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsumptionRoute = ConsumptionRouteImport.update({
  id: '/consumption',
  path: '/consumption',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MeterRoute = MeterRouteImport.update({
  id: '/meter',
  path: '/meter',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/consumption': typeof ConsumptionRoute
  '/login': typeof LoginRoute
  '/meter': typeof MeterRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/consumption': typeof ConsumptionRoute
  '/login': typeof LoginRoute
  '/meter': typeof MeterRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bills': typeof BillsRoute
  '/consumption': typeof ConsumptionRoute
  '/login': typeof LoginRoute
  '/meter': typeof MeterRoute
  '/payments': typeof PaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills' | '/consumption' | '/login' | '/meter' | '/payments'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills' | '/consumption' | '/login' | '/meter' | '/payments'
  id:
    | '__root__'
    | '/'
    | '/bills'
    | '/consumption'
    | '/login'
    | '/meter'
    | '/payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsRoute: typeof BillsRoute
  ConsumptionRoute: typeof ConsumptionRoute
  LoginRoute: typeof LoginRoute
  MeterRoute: typeof MeterRoute
  PaymentsRoute: typeof PaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consumption': {
      id: '/consumption'
      path: '/consumption'
      fullPath: '/consumption'
      preLoaderRoute: typeof ConsumptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meter': {
      id: '/meter'
      path: '/meter'
      fullPath: '/meter'
      preLoaderRoute: typeof MeterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsRoute: BillsRoute,
  ConsumptionRoute: ConsumptionRoute,
  LoginRoute: LoginRoute,
  MeterRoute: MeterRoute,
  PaymentsRoute: PaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
